// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.BackstageTabItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.Button.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.CheckBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.ComboBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.DropDownButton.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.GalleryItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.InRibbonGallery.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.MenuItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.RadioButton.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.RibbonControl.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.RibbonGroupBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.RibbonTabItem.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.TextBox.KeyTipProperty")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0001:Backing field for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~F:Modern.ToggleButton.KeyTipProperty")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.BackstageTabItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.Button.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.CheckBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.ComboBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.DropDownButton.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.GalleryItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.InRibbonGallery.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.MenuItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.RadioButton.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.RibbonControl.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.RibbonGroupBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.RibbonTabItem.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.TextBox.KeyTip")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("WpfAnalyzers.DependencyProperty", "WPF0003:CLR property for a DependencyProperty should match registered name.", Justification = "Exception", Scope = "member", Target = "~P:Modern.ToggleButton.KeyTip")]